### ISSUE TITLE
Exception when taking screenshot

### ISSUE THREAD

**Issue by bayu01** [ebergstedt/OverwatchTeamCounter#1]
An unhandled exception of type 'System.Runtime.InteropServices.ExternalException' occurred in System.Drawing.dll

`System.Runtime.InteropServices.ExternalException was unhandled
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=A generic error occurred in GDI+.
  Source=System.Drawing
  StackTrace:
       at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
       at System.Drawing.Image.Save(String filename, ImageFormat format)
       at Ebergstedt.Overwatch.Counters.BitmapTransformer.TransformBitmapToJpg(Bitmap bitmap) in C:\cygwin64\home\Pedro\OverwatchTeamCounter\src\Ebergstedt.Overwatch.Counters\BitmapTransformer.cs:line 22
       at Ebergstedt.Overwatch.Counters.ScreenCapturer.GetActiveScreenCapture(Rectangle bounds) in C:\cygwin64\home\Pedro\OverwatchTeamCounter\src\Ebergstedt.Overwatch.Counters\ScreenCapturer.cs:line 31
       at Ebergstedt.Overwatch.ConsoleApp.Program.Main(String[] args) in C:\cygwin64\home\Pedro\OverwatchTeamCounter\src\Ebergstedt.Overwatch.ConsoleApp\Program.cs:line 57
  InnerException: 
`

**Comment by ebergstedt** [comment]
Use windows. You provide no information, but I guess you use a linux distro that has problems with System.Drawing
